title:            "ship.sh"
description:      "Official support webpage for the project 'ship'. Developed and maintained by xtonousou."
show_downloads:   true
google_analytics: "UA-104956050-1"
lang:             "en-US"

href:
  google_analytics: "https://www.google-analytics.com/analytics.js"
  favicon:          "assets/images/favicon.ico"
  style:            "assets/css/style.css"
  animatecss:       "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"
  fontawesome:      "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  jquery:           "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"
  respond:          "assets/js/respond.js"
  totop:            "assets/js/totop.js"
  html5:            "https://html5shiv.googlecode.com/svn/trunk/html5.js"
  ie:               "assets/css/ie.css"
  logo:             "assets/images/logo-with-text.png"
  jekyll:           "https://jekyllrb.com"
  gitpages:         "https://pages.github.com"
  fontawesome_:     "http://fontawesome.io"
  animatecss_:      "https://daneden.github.io/animate.css"
  ruby:             "https://www.ruby-lang.org/en"

project:
  version:        "2.6"
  license:        "GPL v3+"
  bash:           "3.2+"
  main_url:       "https://raw.githubusercontent.com/xtonousou/ship/master/ship.sh"
  license_url:    "license.md"
  bash_url:       "http://tldp.org/LDP/abs/html/bashver3.html#AEN20987"
  paypal_url:     "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NJ4VLBTM8FB4C"
  say_thanks_url: "https://saythanks.io/to/xtonousou"
  aur_url:        "https://aur.archlinux.org/packages/ship"

shield:
  version_shield:     "https://img.shields.io/badge/version-2.6-blue.svg?style=flat-square&colorA=13818d&colorB=44c2c7"
  license_shield:     "https://img.shields.io/badge/license-GPL%20v3%2B-yellow.svg?style=flat-square&colorA=13818d&colorB=44c2c7"
  bash_shield:        "https://img.shields.io/badge/bash-3.2+-lightgrey.svg?style=flat-square&colorA=13818d&colorB=44c2c7"
  paypal_shield:      "https://img.shields.io/badge/paypal-donate-blue.svg?style=flat-square&colorA=13818d&colorB=44c2c7"
  say_thanks_shield:  "https://img.shields.io/badge/say%20thanks-!-blue.svg?style=flat-square&colorA=13818d&colorB=44c2c7"
  aur_shield:         "https://img.shields.io/aur/version/ship.svg?style=flat-square&colorA=13818d&colorB=44c2c7"

github:
  repository_name: "ship"
  tagline:         "a simple, handy network addressing multitool with plenty of features"
  owner_name:      "xtonousou"
  owner_url:       "https://github.com/xtonousou"
  repository_url:  "https://github.com/xtonousou/ship"
  master_zip:      "https://github.com/xtonousou/ship/archive/master.zip"
  dev_zip:         "https://github.com/xtonousou/ship/archive/dev.zip"
  pubkey:          "4C18E0B77A122AD9"

compatibility:
  arch_from:   "4.7.5-1"
  arch_to:     "4.12.8-2"
  centos_from: "7"
  centos_to:   "7"
  debian_from: "7"
  debian_to:   "8"
  kali_from:   "2016.2"
  kali_to:     "2016.2"
  ubuntu_from: "14.04.3"
  ubuntu_to:   "16.04.1"
